services:
  postgres:
    image: 'postgres:16-alpine'
    environment:
      - 'POSTGRES_DB=${TTT_DB_NAME}'
      - 'POSTGRES_PASSWORD=${TTT_DB_PASSWORD}'
      - 'POSTGRES_USER=${TTT_DB_USERNAME}'
    ports:
      - '5434:5432' # Host port changed to 5434 to avoid conflict
  redis:
    image: 'redis/redis-stack-server:7.2.0-v10'
    ports:
      - '6379:6379'
    volumes:
      - redis_:/data
    command: redis-server --appendonly yes --protected-mode no

volumes:
  redis_: