spring:
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1
    driverClassName: org.h2.Driver
    username: sa
    password: password
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: false
    database-platform: org.hibernate.dialect.H2Dialect
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${TTT_GOOGLE_CLIENT_ID:missing-client-id}
            client-secret: ${TTT_GOOGLE_CLIENT_SECRET:missing-client-secret}
            scope:
              - email
              - profile

application:
  security:
    jwt:
      secret-key: ${TTT_JWT_SECRET:743677397A24432646294A404E635266556A586E3272357538782F413F442847}
      expiration: 86400000 # 1 day
    oauth2:
      redirect-uri: ${TTT_OAUTH2_REDIRECT_URI:http://localhost:3000/oauth2/redirect}
